package entity;
// Generated 22-oct-2016 15:48:58 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="USUARIOS"
    ,schema="ALE1"
)
public class Usuarios  implements java.io.Serializable {


     private String nombreUsuario;
     private String password;
     private String codRol;
     private String codPersona;

    public Usuarios() {
    }

	
    public Usuarios(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public Usuarios(String nombreUsuario, String password, String codRol, String codPersona) {
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.codRol = codRol;
       this.codPersona = codPersona;
    }
   
     @Id 

    
    @Column(name="NOMBRE_USUARIO", unique=true, nullable=false, length=20)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="COD_ROL", length=30)
    public String getCodRol() {
        return this.codRol;
    }
    
    public void setCodRol(String codRol) {
        this.codRol = codRol;
    }

    
    @Column(name="COD_PERSONA", length=20)
    public String getCodPersona() {
        return this.codPersona;
    }
    
    public void setCodPersona(String codPersona) {
        this.codPersona = codPersona;
    }




}


