package entidades;
// Generated 10-21-2016 10:03:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Especialidad generated by hbm2java
 */
@Entity
@Table(name="ESPECIALIDAD"
    ,schema="SYSTEM"
)
public class Especialidad  implements java.io.Serializable {


     private String codEspecialidad;
     private String nombre;

    public Especialidad() {
    }

    public Especialidad(String codEspecialidad, String nombre) {
       this.codEspecialidad = codEspecialidad;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="COD_ESPECIALIDAD", unique=true, nullable=false, length=10)
    public String getCodEspecialidad() {
        return this.codEspecialidad;
    }
    
    public void setCodEspecialidad(String codEspecialidad) {
        this.codEspecialidad = codEspecialidad;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


