package entidades;
// Generated 10-21-2016 10:03:23 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Medico generated by hbm2java
 */
@Entity
@Table(name="MEDICO"
    ,schema="SYSTEM"
)
public class Medico  implements java.io.Serializable {


     private BigDecimal codMedico;
     private Empleado empleado;
     private String codEspecialidad;

    public Medico() {
    }

	
    public Medico(BigDecimal codMedico) {
        this.codMedico = codMedico;
    }
    public Medico(BigDecimal codMedico, Empleado empleado, String codEspecialidad) {
       this.codMedico = codMedico;
       this.empleado = empleado;
       this.codEspecialidad = codEspecialidad;
    }
   
     @Id 

    
    @Column(name="COD_MEDICO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodMedico() {
        return this.codMedico;
    }
    
    public void setCodMedico(BigDecimal codMedico) {
        this.codMedico = codMedico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODIGO_EMPLEADO")
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="COD_ESPECIALIDAD", length=1024)
    public String getCodEspecialidad() {
        return this.codEspecialidad;
    }
    
    public void setCodEspecialidad(String codEspecialidad) {
        this.codEspecialidad = codEspecialidad;
    }




}


